---
title: "Lab 00 - Hello IDS!"
author: "Tom Cummings"
date: "`r Sys.Date()`"
output: html_document
---


```{r load-packages, message=FALSE}
library(tidyverse) 
```


We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Tom Cummings", "Fin Mclauchel", "Harry English", 
           "Finn Webb"),
  github_username = c("tom-rex", "Finnmc3", "HarryEnglish", 
                      "Cameronfischer05"), 
  colour = c("Red", "Blue", "Blue", 
             "Blue"),
  hobby = c("Data science", "Chasing people", "running", 
            "Jumping"),
  favourite_number = c(6, 1, 3, 7)
  )

team_data
```


We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```



Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Usernames", 
          y = "Favourite Number",
          title = "Each members favourite Number")
```


```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

